# Generated by Django 4.2.11 on 2024-04-02 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_accounts'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounts',
            name='when',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
