# Generated by Django 4.2.11 on 2024-04-04 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_accounts_when'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poster', models.PositiveBigIntegerField(default=0)),
                ('reply', models.PositiveBigIntegerField(default=0)),
                ('when', models.DateTimeField()),
                ('text', models.CharField()),
                ('post_type', models.CharField(max_length=10)),
            ],
        ),
        migrations.DeleteModel(
            name='BooBqk',
        ),
    ]
