# Generated by Django 4.2.11 on 2024-04-04 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_rename_us_id_accounts_uid'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounts',
            name='picurl',
            field=models.CharField(default='nope', max_length=300),
        ),
    ]
