# Generated by Django 4.2.11 on 2024-04-07 20:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myapp', '0009_chat_us_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery_category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=300)),
                ('Desc', models.CharField(max_length=300)),
                ('when', models.DateTimeField(auto_now=True)),
                ('picurl', models.CharField(default='nope', max_length=3000)),
                ('uid', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Photos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=300)),
                ('Desc', models.CharField(max_length=300)),
                ('when', models.DateTimeField(auto_now=True)),
                ('picurl', models.CharField(default='nope', max_length=3000)),
                ('uid', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Gallery_comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Text', models.CharField(max_length=300)),
                ('Desc', models.IntegerField(null=True)),
                ('when', models.DateTimeField(default=django.utils.timezone.now)),
                ('Author', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('Photo_id', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='myapp.gallery_category')),
            ],
        ),
    ]
